[package]
name = "verifier"
version = "0.1.0"
authors = ["Anjan Roy <anjan.roy@matic.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[lib]
crate-type = ["cdylib"]
